// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ColorsPanel: typeof import('./src/components/ColorsPanel.vue')['default']
    ConfigPanel: typeof import('./src/components/ConfigPanel.vue')['default']
    ExportPanel: typeof import('./src/components/ExportPanel.vue')['default']
    HomeIndex: typeof import('./src/components/HomeIndex.vue')['default']
    RadiusPanel: typeof import('./src/components/RadiusPanel.vue')['default']
    ShadowPanel: typeof import('./src/components/ShadowPanel.vue')['default']
    TypographyPanel: typeof import('./src/components/TypographyPanel.vue')['default']
  }
}

export {}
