// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ColorsPanel: typeof import('./src/components/ColorsPanel.vue')['default']
    ExportPanel: typeof import('./src/components/ExportPanel.vue')['default']
    HomeIndex: typeof import('./src/components/HomeIndex.vue')['default']
    RadiusPanel: typeof import('./src/components/RadiusPanel.vue')['default']
    ShadowPanel: typeof import('./src/components/ShadowPanel.vue')['default']
    TypographyPanel: typeof import('./src/components/TypographyPanel.vue')['default']
  }
}

export {}
